export enum Links {
  Live = "Live",
  Github = "Github",
  React = "React",
  Node = "Node",
  Typescript = "Typescript",
  Nextjs = "Nextjs",
  Cypress = "Cypress",
  Postgresql = "Postgresql",
  Paypal = "Paypal",
  Jest = "Jest",
  Redux = "Redux",
  StyledComponents = "Styled-components",
  Bootstrap = "Bootstrap",
  Express = "Express",
  Redis = "Redis",
  Numpy = "Numpy",
  TensorFlow = "TensorFlow",
  Python = "Python",
}
