export enum Links {
  Live = "Live",
  Github = "Github",
  React = "React",
  Node = "Node",
  Golang = "Golang",
  Typescript = "Typescript",
  Nextjs = "Nextjs",
  Cypress = "Cypress",
  Postgresql = "Postgresql",
  Paypal = "Paypal",
  Jest = "Jest",
  Redux = "Redux",
  StyledComponents = "Styled-components",
  Bootstrap = "Bootstrap",
  Express = "Express",
  Redis = "Redis",
  Numpy = "Numpy",
  TensorFlow = "TensorFlow",
  Python = "Python",
  Vue = "Vue",
  Gatsby = "Gatsby",
  Mui = "Material UI",
  Git = "Git",
  Html = "HTML5",
  CSS = "CSS",
  Docker = "Docker",
  Markdown = "Markdown",
  Java = "Java",
  Spring = "Java Spring",
  Aws = "AWS",
  VSCode = "VSCode",
  MongoDB = "MongoDB",
  MySQL = "MySQL",
  Ethereum = "Ethereum",
  Sass = "Sass",
  Stripe = 'Stripe',
  NestJS = 'Nestjs',
  Javascript = 'Javascript',
  Createreactapp = 'Create React App',
  Prettier = 'Prettier',
  Eslint = 'Eslint',
  WebComponents = 'Web Components'
}

export interface Link {
  kind: Links;
  url: string;
}
